version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: poridhi-backend:latest
    command: uvicorn main:app --workers 2 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=http://qdrant:6333
    depends_on:
      - qdrant
      - prometheus
      - grafana
    restart: unless-stopped
    networks:
      - poridhi-ai-net
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 512M

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - poridhi-ai-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    restart: unless-stopped
    networks:
      - poridhi-ai-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - poridhi-ai-net

volumes:
  qdrant_data:
  prometheus_data:
  grafana_data:

networks:
  poridhi-ai-net:
    external: true
