services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000 # port 8000 is inside Docker
    networks:
      - poridhi-ai-net
    depends_on:
      - backend
      
  # Reference the existing backend service from the backend docker-compose
  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: backend
      
  qdrant:
    extends:
      file: ./backend/docker-compose.yml
      service: qdrant
      
  prometheus:
    extends:
      file: ./backend/docker-compose.yml
      service: prometheus
      
  grafana:
    extends:
      file: ./backend/docker-compose.yml
      service: grafana

networks:
  poridhi-ai-net:
    external: true
    
volumes:
  qdrant_data:
  prometheus_data:
  grafana_data:
